import { NextPage } from "next";
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Footer from "./Footer";
import Header from "./Header";

type PropsType = {
    title?: string
    keywords?: string
    icon?: string
}
const MyContainer: NextPage<PropsType> = ({ children, title = "NextJs", icon = "/favicon.ico", keywords = "NextJS" }) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                {/* @ts-ignore */}
                <meta keywords={keywords}></meta>
                <link rel="icon" href={icon} />
            </Head>
            <Header />
            {children}

            <Footer />
        </>
    )
}
export default MyContainer